%%{init: {
  'theme':'base',
  'gitGraph': {
    'showBranches': true,
    'showCommitLabel':false
  },
  'themeVariables': {
    'tagLabelFontSize': '18px'
  }
}}%%

gitGraph
   commit
   commit
   commit
   commit
   commit
   commit
   commit
   commit
   commit
   commit
   commit
   commit
   commit
